services:
  mongodb:
    image: mongo:latest
    container_name: finance_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: budgetDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth

volumes:
  mongodb_data:
    name: finance_mongodb_data